<?php

// Ex-8
$list1 = "4, 5, 6, 7";
$list2 = "4, 5, 7, 8";

// Using Built-in functions
$list1 = explode(", ", $list1);
$list2 = explode(", ", $list2);

// Join the unique array generated by merging the 2 arrays list1 and list2 after exploding by ", "

$res = implode(", ", array_unique(array_merge($list1, $list2)));

echo $res . "\n";

// Scratch
$res = $list1;

// Add all list2 values that are not already in res - res = $list1 - .
foreach ($list2 as $val) {
    $found = false;
    foreach ($res as $resVal) {
        if ($val === $resVal) {
            $found = true;
        }
    }

    if (!$found) {
        $res[] = $val;
    }
}
$resStr = "";
// use sort($res) to sort the array
foreach ($res as $val) {
    $resStr .= $val . ", ";
}

echo $resStr . "\n";
