-- MySQL Script generated by MySQL Workbench
-- Tue 24 Aug 2021 10:37:02 AM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`faculty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`faculty` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`faculty_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instructor` (
  `instructor_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `faculty_faculty_id` INT NOT NULL,
  PRIMARY KEY (`instructor_id`),
  INDEX `fk_instructor_faculty1_idx` (`faculty_faculty_id` ASC),
  CONSTRAINT `fk_instructor_faculty1`
    FOREIGN KEY (`faculty_faculty_id`)
    REFERENCES `mydb`.`faculty` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`degree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`degree` ;

CREATE TABLE IF NOT EXISTS `mydb`.`degree` (
  `degree_id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NULL,
  `university` VARCHAR(45) NULL,
  `field` VARCHAR(45) NULL,
  `degree_type` VARCHAR(3) NULL,
  `instructor_instructor_id` INT NOT NULL,
  PRIMARY KEY (`degree_id`, `instructor_instructor_id`),
  INDEX `fk_degree_instructor_idx` (`instructor_instructor_id` ASC),
  CONSTRAINT `fk_degree_instructor`
    FOREIGN KEY (`instructor_instructor_id`)
    REFERENCES `mydb`.`instructor` (`instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
